# Generated by Django 4.1.7 on 2023-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_post_alter_women_options_women_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo2',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2'),
            preserve_default=False,
        ),
    ]
