# Generated by Django 4.1.7 on 2023-07-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_rename_women_product_alter_customer_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Women',
        ),
    ]
