# Generated by Django 4.1.7 on 2023-07-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_rename_compled_order_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddres',
            new_name='ShippingAddress',
        ),
    ]
