# Generated by Django 4.1.7 on 2023-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_rename_shippingaddres_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
