# Generated by Django 4.1.7 on 2023-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_women_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
