# Generated by Django 4.1.7 on 2023-07-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
    ]
