# Generated by Django 4.1.7 on 2023-07-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_remove_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='number',
        ),
    ]
