# Generated by Django 4.1.7 on 2023-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0016_rename_state_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
