# Generated by Django 4.1.7 on 2023-07-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0018_remove_shippingaddress_phone_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='phone',
        ),
    ]
